# Custom Language File for Launcher Customizer

[ejs.app]
title = "Shinobi Origins Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Shinobi Origins !"
welcomeDescription = "Notre objectif: Pousser le RolePlay Naruto à son paroxysme."
welcomeDescCTA = "Vous n'êtes plus qu'à quelques clics de notre serveur."
